config/routes.rb
Rails.application.routes.draw do
  # get 'review/create'
  # get 'review/edit'
  # get 'review/update'
  # get 'review/destroy'
  root to: "products#index"

  resources :products do
  resources :reviews, except: [:index, :new, :show]
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :products
 resources :users
 resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :reviews

  def price_in_dollars
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("$%.2f", price_in_dollars)
  end

  validates :name, presence: { message: "field must be filled out!" }
  validates :description, presence: { message: "field must be filled out!" }
  validates :price_in_cents, presence: { message: "field must be filled out!" }
  validates :price_in_cents, numericality: {only_integer: true}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user

    validates :description, presence: { message: "field must be filled out!" }
    validates :product_id, presence: { message: "field must be filled out!" }


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :reviews

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_url
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new
    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]
    if @product.save
        flash[:notice] = "Product saved !"
       redirect_to '/products'
     else
       render :new
    end

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]
    if @product.save
      flash[:notice] = "Product updated !"
       redirect_to "/products/#{@product.id}"
     else
       render :edit
    end


  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    if @product.destroy
      flash[:notice] = "Product Deleted !"
    redirect_to "/products"
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :ensure_logged_in
  before_action :load_review, only: [:edit, :update, :destroy]
  before_action :ensure_user_owns_review

  def create
    @review = Review.new
    @product = Product.find(params[:product_id])
    @review.product_id = params[:product_id]
    @review.description = params[:review][:description]
    @review.user = current_user
    if @review.save
      flash[:notice] = "Review saved !"
      redirect_to "/products/#{@review.product_id}"
    else
      @product = Product.find(params[:product_id])
      render "products/show"
    end
  end

  def edit
    @product = Product.find(params[:product_id])
  end

  def update
    @review.product_id = params[:product_id]
    @review.description = params[:review][:description]
    if @review.save
      flash[:notice] = "Review updated !"
      redirect_to "/products/#{@review.product_id}"
    else
      @product = Product.find(params[:product_id])
      render "products/show"
    end
  end

  def destroy
    @product = Product.find(params[:product_id])
    @review.destroy
    if @review.destroy
    redirect_to "/products/#{@product.id}"
    end
  end

  def load_review
    @review = Review.find(params[:id])
  end

  def ensure_user_owns_review
    unless current_user == @review.user
      flash[:alert] = "Please log in"
      redirect_to new_session_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to products_url, notice: "Logged in!"
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      redirect_to root_url
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_controller_helper.rb
module ProductsControllerHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <h2><%= link_to('Home','/products')%> | <%= link_to('Create new product',"/products/new")%></h2>
        <p class="userinfo">
          <% if current_user %>
            Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
          <% else %>
            <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
          <% end %>
        </p>
        <hr>
        <br>
      </nav>
      <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/products/create.html.erb
<h1>ProductsController#create</h1>
<p>Find me in app/views/products_controller/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>ProductsController#destroy</h1>
<p>Find me in app/views/products_controller/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Edit <%=@product.name%> page</h1>
<%=  link_to("Back to Index", "/products") %>
<hr>
<!-- <p>Find me in app/views/products_controller/new.html.erb</p> -->


<%= form_for(@product) do |f| %>


<p> <%= f.label :name %>
    <%= f.text_field :name %> </p>

<p> <%= f.label :description %>
    <%= f.text_field :description %> </p>

<p> <%= f.label :price_in_cents %>
    <%= f.number_field :price_in_cents %> </p>

<p> <%= f.submit "UPDATE"%></p>

<% end %>

<%= @product.errors.full_messages.first if @product.errors.any? %>

app/views/products/index.html.erb
<h1>Welcome to products index page!</h1>

<div>
  <% @products.each do |product|%>
    <ul>
      <li>
      <h2><%=link_to("#{product.name}","/products/#{product.id}") %></h2>

      <h2><%=product.description%></h2>
      <h2><%=product.price_in_dollars%></h2>
      </li>
      <br>
    </ul>
  <%end%>
</div>

app/views/products/new.html.erb
<h1>ProductsController#new</h1>
<%=  link_to("Back to Index", "/products") %>
<hr>
<!-- <p>Find me in app/views/products_controller/new.html.erb</p> -->


<%= form_for(@product) do |f| %>


<p>  <%= f.label :name %>
  <%= f.text_field :name %> </p>

<p>  <%= f.label :description %>
  <%= f.text_field :description %> </p>

<p>  <%= f.label :price_in_cents %>
  <%= f.number_field :price_in_cents %> </p>

<p> <%= f.submit "SAVE"%></p>
<% end %>

<%= @product.errors.full_messages.first if @product.errors.any? %>

app/views/products/show.html.erb
<h1>Product: <%= @product.name %></h1>
<hr>
<div>
<p> Description: <%= @product.description %></p>
<p> Price: <%= @product.price_in_cents %></p>
</div>

<%= link_to('Edit', "/products/#{@product.id}/edit") %> | <%= link_to('Delete',"/products/#{@product.id}", method: :delete) %>
<hr>

<h3>Reviews:<h3>
<%@product.reviews.each do |review|%>
  <ul>
    <li>
      <p><%=review.description%></p>
      <p><%=review.created_at%></p>
      <%= link_to("Edit", edit_product_review_path(@product,review)) %>
      <%= link_to("delete", product_review_url(@product,review), method: :delete) %>
    </li>
    <br>
  </ul>

<%end%>

<h2>New Review</h2>
<%= render 'reviews/form', product: @product, review: @review %>

app/views/products/update.html.erb
<h1>ProductsController#update</h1>
<p>Find me in app/views/products_controller/update.html.erb</p>

app/views/reviews/_form.html.erb
<%= form_for([product, review]) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/create.html.erb
<h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Review#destroy</h1>
<p>Find me in app/views/review/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Edit review for <%= @product.name %> </h1>

<%= render 'reviews/form', product: @product, review: @review %>

app/views/reviews/update.html.erb
<h1>Review#update</h1>
<p>Find me in app/views/review/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

  <% if @user.errors.any? %>
  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <%= form_for @user do |f| %>

  <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

  <div>
  <%= f.submit 'Sign Up' %>
  </div>

  <% end %>